name: AdvancedRealm
author: iPazu
version: ${version}
main: fr.ipazu.advancedrealm.Main
api-version: 1.21
commands:
  realm:
  visit:
  configrealm:
dependencies:
  server:
    WorldEdit:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
